### PR TITLE
DO NOT MERGE: break build on windows

### PR DESCRIPTION
**Pull request by nico**
testing https://ci.appveyor.com/project/nico/ninja

### CODE REVIEW

**Comment by sgraham** [comment]
asdf lgtm!

I guess it doesn't automatically do pull requests, darn.

...

Looks like you have to manually set up the webhook? http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

**Comment by nico** [comment]
Hm, I think Evan and I once tried to get me access to webhooks and couldn't figure out how. Oh well, maybe he happens to see this and sets them up ;-)

**Comment by martine** [comment]
What do I need to do?

**Comment by nico** [comment]
http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

**Comment by nico** [comment]
woohoo :-)

**Pull request closed without merging**
