### PR TITLE
Check pending SIGINT after ppoll/pselect

### PR DESCRIPTION
**Pull request by tzik**
ppoll/pselect prioritizes file descriptor events over
a signal delivery. So a flood of events prevents ninja
from reacting keyboard interruption by the user.

This CL adds a check for pending keyboard interruptions after
file descriptor events.

### CODE REVIEW

**Comment by nicolasdespres** [comment]
Thx! for writing the patch.

**Comment by nico** [comment]
@pcc Does this make sense to you?

**Comment by pcc** [comment]
Seems reasonable.

**Comment by nicolasdespres** [comment]
A link to the forum and the related issue should be added for further explanation: 
https://groups.google.com/forum/#!searchin/ninja-build/Does$20anybody$20has$20experienced$20ninja$20not$20interrupted$20when$20hitting$20control-c$3F/ninja-build/leEnr095PeA/abUdsJr_PawJ
and
https://github.com/martine/ninja/issues/893

**Pull request merged**
